//! Enable and start `cpn-installer.service` after a successful install.
//!
//! Package `%post` only runs `daemon-reload`; without this hook the panel does
//! not survive SSH disconnect (CLI exit) or reboot. Respects `--allow-remote`
//! / `CPN_ALLOW_REMOTE=1` via a systemd drop-in and a data-dir preference.

use crate::paths;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

/// systemd unit name shipped in packaging.
pub const UNIT_NAME: &str = "cpn-installer.service";

const VENDOR_UNIT: &str = include_str!("../packaging/cpn-installer.service");
const LIB_UNIT_PATH: &str = "/usr/lib/systemd/system/cpn-installer.service";
const ETC_UNIT_PATH: &str = "/etc/systemd/system/cpn-installer.service";
const DROPIN_DIR: &str = "/etc/systemd/system/cpn-installer.service.d";
const DROPIN_REMOTE_PATH: &str = "/etc/systemd/system/cpn-installer.service.d/10-allow-remote.conf";

const ALLOW_REMOTE_DROPIN: &str = "\
# Generated by cpn-installer after an allow-remote install.
# Removes localhost-only bind so VirtualBox NAT / lab host forwards work.
# Trusted networks only (HTTP without TLS). Prefer SSH -L when possible.
[Service]
Environment=CPN_ALLOW_REMOTE=1
";

/// How aggressively to start the unit after enable.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PanelServiceMode {
    /// CLI finished and will exit: enable and start so `/login` stays up.
    EnableAndStart,
    /// Web UI still owns the process: enable always; start only if inactive
    /// (start may fail when this process already holds the port; that is OK).
    EnablePreferRunning,
}

/// Result of post-install systemd wiring (no secrets).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PanelServiceReport {
    pub unit_written: bool,
    pub allow_remote: bool,
    pub enabled: bool,
    pub started: bool,
    pub message: String,
}

fn is_root() -> bool {
    #[cfg(unix)]
    {
        unsafe { libc::geteuid() == 0 }
    }
    #[cfg(not(unix))]
    {
        false
    }
}

fn under_systemd() -> bool {
    env::var_os("INVOCATION_ID").is_some()
}

fn allow_remote_preference_path() -> PathBuf {
    paths::join_data("allow_remote")
}

/// True when CLI/env requested remote bind, or a prior install persisted it.
pub fn allow_remote_requested() -> bool {
    if env::args().any(|arg| arg == "--allow-remote" || arg == "--listen-all") {
        return true;
    }
    if env::var("CPN_ALLOW_REMOTE").ok().as_deref() == Some("1") {
        return true;
    }
    load_allow_remote_preference()
}

pub fn load_allow_remote_preference() -> bool {
    let path = allow_remote_preference_path();
    let Ok(raw) = fs::read_to_string(&path) else {
        return false;
    };
    matches!(raw.trim(), "1" | "true" | "yes" | "on")
}

pub fn save_allow_remote_preference(enabled: bool) -> Result<(), String> {
    let path = allow_remote_preference_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Could not create data directory {}: {error}",
                parent.display()
            )
        })?;
    }
    if !enabled {
        let _ = fs::remove_file(&path);
        return Ok(());
    }
    let mut options = fs::OpenOptions::new();
    options.write(true).create(true).truncate(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = options
        .open(&path)
        .map_err(|error| format!("Could not save allow_remote preference: {error}"))?;
    file.write_all(b"1\n")
        .map_err(|error| format!("Could not save allow_remote preference: {error}"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&path, fs::Permissions::from_mode(0o600));
    }
    Ok(())
}

fn write_file(path: &Path, contents: &str, mode: u32) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("Could not create directory {}: {error}", parent.display()))?;
    }
    let mut options = fs::OpenOptions::new();
    options.write(true).create(true).truncate(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(mode);
    }
    let mut file = options
        .open(path)
        .map_err(|error| format!("Could not write {}: {error}", path.display()))?;
    file.write_all(contents.as_bytes())
        .map_err(|error| format!("Could not write {}: {error}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(path, fs::Permissions::from_mode(mode));
    }
    Ok(())
}

/// Ensure the vendor unit exists (RPM/DEB normally ship it; binary-only installs may not).
pub fn ensure_unit_file() -> Result<bool, String> {
    let lib = Path::new(LIB_UNIT_PATH);
    let etc = Path::new(ETC_UNIT_PATH);
    if lib.is_file() || etc.is_file() {
        return Ok(false);
    }
    write_file(etc, VENDOR_UNIT, 0o644)?;
    Ok(true)
}

fn apply_allow_remote_dropin(allow_remote: bool) -> Result<(), String> {
    let dropin = Path::new(DROPIN_REMOTE_PATH);
    if allow_remote {
        fs::create_dir_all(DROPIN_DIR)
            .map_err(|error| format!("Could not create systemd drop-in directory: {error}"))?;
        write_file(dropin, ALLOW_REMOTE_DROPIN, 0o644)?;
    } else if dropin.is_file() {
        // Keep an existing operator drop-in if preference is false but file was
        // hand-edited; only remove when we previously managed it (contains marker).
        if let Ok(existing) = fs::read_to_string(dropin)
            && existing.contains("Generated by cpn-installer")
        {
            let _ = fs::remove_file(dropin);
        }
    }
    Ok(())
}

fn systemctl(args: &[&str]) -> Result<(), String> {
    let status = Command::new("systemctl")
        .args(args)
        .status()
        .map_err(|error| format!("Could not run systemctl {}: {error}", args.join(" ")))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("systemctl {} failed", args.join(" ")))
    }
}

fn unit_is_active() -> bool {
    Command::new("systemctl")
        .args(["is-active", "--quiet", UNIT_NAME])
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

/// English operator hints (no passwords). Used by end-of-install banners.
pub fn post_install_service_hints(port: u16, allow_remote: bool) -> Vec<String> {
    let mut lines = vec![
        format!("systemd: enabled {UNIT_NAME} (starts on boot)"),
        format!("Local login: http://127.0.0.1:{port}/login"),
        format!(
            "VirtualBox NAT tip: if host forwards 2089->guest {port}, open http://127.0.0.1:2089/login on the host"
        ),
    ];
    if allow_remote {
        lines.push("Listen: 0.0.0.0 (CPN_ALLOW_REMOTE=1 persisted in systemd drop-in)".into());
    } else {
        lines.push(
            "Listen: 127.0.0.1 (for NAT without SSH -L, reinstall/start with --allow-remote or CPN_ALLOW_REMOTE=1)"
                .to_string(),
        );
    }
    lines.push(format!(
        "Manage: systemctl status {UNIT_NAME} | systemctl restart {UNIT_NAME}"
    ));
    lines
}

/// Wire systemd after a successful web or CLI install.
pub fn ensure_panel_service_after_install(
    mode: PanelServiceMode,
    allow_remote: bool,
) -> Result<PanelServiceReport, String> {
    if cfg!(windows) {
        return Ok(PanelServiceReport {
            unit_written: false,
            allow_remote,
            enabled: false,
            started: false,
            message: "systemd panel service is Linux-only; skipped on Windows.".into(),
        });
    }
    if !is_root() {
        return Ok(PanelServiceReport {
            unit_written: false,
            allow_remote,
            enabled: false,
            started: false,
            message: "Not root: skipped enabling cpn-installer.service.".into(),
        });
    }

    let unit_written = ensure_unit_file()?;
    save_allow_remote_preference(allow_remote)?;
    apply_allow_remote_dropin(allow_remote)?;
    let _ = systemctl(&["daemon-reload"]);

    systemctl(&["enable", UNIT_NAME]).map_err(|error| {
        format!("{error} (is the unit installed under /usr/lib/systemd/system?)")
    })?;

    let mut started = false;
    let mut message = format!("{UNIT_NAME} enabled for multi-user.target.");

    let should_try_start = match mode {
        PanelServiceMode::EnableAndStart => true,
        PanelServiceMode::EnablePreferRunning => !unit_is_active() && !under_systemd(),
    };

    if should_try_start {
        match systemctl(&["start", UNIT_NAME]) {
            Ok(()) => {
                started = true;
                message = format!("{UNIT_NAME} enabled and started.");
            }
            Err(error) => {
                // Web UI often already holds the listen port outside systemd.
                message = format!(
                    "{UNIT_NAME} enabled; start deferred ({error}). If /login is already up in this process, it stays until reboot; systemd starts it next boot."
                );
            }
        }
    } else if unit_is_active() || under_systemd() {
        started = true;
        message = format!("{UNIT_NAME} enabled (already running under systemd).");
    }

    Ok(PanelServiceReport {
        unit_written,
        allow_remote,
        enabled: true,
        started,
        message,
    })
}

/// Best-effort wrapper for install paths (logs warnings, never fails the install).
pub fn ensure_panel_service_best_effort(mode: PanelServiceMode, allow_remote: bool) {
    match ensure_panel_service_after_install(mode, allow_remote) {
        Ok(report) => {
            if report.unit_written {
                eprintln!("cpn-installer: wrote missing {UNIT_NAME} unit file");
            }
            println!("  {}", report.message);
            if report.allow_remote {
                println!("  Remote bind persisted (CPN_ALLOW_REMOTE=1 systemd drop-in).");
            }
        }
        Err(error) => {
            eprintln!("cpn-installer: could not enable {UNIT_NAME}: {error}");
            eprintln!("cpn-installer: start manually with: systemctl enable --now {UNIT_NAME}");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendor_unit_mentions_web_and_wanted_by() {
        assert!(VENDOR_UNIT.contains("ExecStart=/usr/bin/cpn-installer --web"));
        assert!(VENDOR_UNIT.contains("WantedBy=multi-user.target"));
        assert!(!VENDOR_UNIT.contains('\u{2014}'));
        assert!(!VENDOR_UNIT.contains('\u{2013}'));
    }

    #[test]
    fn allow_remote_dropin_sets_env() {
        assert!(ALLOW_REMOTE_DROPIN.contains("CPN_ALLOW_REMOTE=1"));
        assert!(ALLOW_REMOTE_DROPIN.contains("Generated by cpn-installer"));
        assert!(!ALLOW_REMOTE_DROPIN.contains('\u{2014}'));
    }

    #[test]
    fn hints_include_login_and_vbox_nat() {
        let lines = post_install_service_hints(2087, false);
        let joined = lines.join("\n");
        assert!(joined.contains("http://127.0.0.1:2087/login"));
        assert!(joined.contains("2089"));
        assert!(joined.contains("systemctl"));
        assert!(!joined.to_lowercase().contains("password"));
        assert!(!joined.contains('\u{2014}'));
    }

    #[test]
    fn hints_mark_allow_remote() {
        let joined = post_install_service_hints(2087, true).join("\n");
        assert!(joined.contains("0.0.0.0"));
        assert!(joined.contains("CPN_ALLOW_REMOTE=1"));
    }
}
